name: ice_lakehouse
version: "1.0.0"
config-version: 2

profile: ice_lakehouse

model-paths: ["models"]
macro-paths: ["macros"]

models:
  ice_lakehouse:
    silver:
      +schema: silver
      +materialized: incremental
      +incremental_strategy: merge
      +file_format: iceberg
    gold:
      +schema: gold
      +materialized: table
      +file_format: iceberg
